# Generated by Django 5.2.10 on 2026-02-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='products',
            new_name='product',
        ),
    ]
